export { Hero } from "./Hero"
export { Bluf } from "./Bluf"
export { Capabilities } from "./Capabilities"
export { CapabilitiesTable } from "./CapabilitiesTable"
export { ElectronicsManufacturing } from "./ElectronicsManufacturing"
export { Products } from "./Products"
export { CaseStudies } from "./CaseStudies"
export { Engineering } from "./Engineering"
export { VaveTeardown } from "./VaveTeardown"
export { Industries } from "./Industries"
export { Quality } from "./Quality"
export { SourcingComparison } from "./SourcingComparison"
export { GlobalSourcing } from "./GlobalSourcing"
export { Engagement } from "./Engagement"
export { FAQ, faqData } from "./FAQ"
export { FinalCTA } from "./FinalCTA"
export { StickyCTA } from "./StickyCTA"
